export default {
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#e5e2e1",
        "on-secondary": "#313030",
        "tertiary-fixed-dim": "#ffb960",
        "tertiary-container": "#a76900",
        "surface-dim": "#131313",
        "on-surface": "#e5e2e1",
        "primary-container": "#66d9ff",
        "secondary": "#c8c6c5",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed": "#1c1b1b",
        "background": "#131313",
        "on-primary": "#003544",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-on-surface": "#313030",
        "outline": "#8ba0a0",
        "secondary-container": "#4a4949",
        "on-tertiary-container": "#ffffff",
        "on-tertiary-fixed": "#2b1700",
        "surface-container": "#201f1f",
        "primary": "#bae6ff",
        "surface-variant": "#353534",
        "on-error": "#690005",
        "on-secondary-container": "#bab8b7",
        "on-surface-variant": "#c0d7d7",
        "surface-tint": "#bae6ff",
        "on-tertiary-fixed-variant": "#653e00",
        "surface": "#131313",
        "on-primary-fixed-variant": "#004e60",
        "secondary-fixed": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "tertiary": "#ffb960",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "primary-fixed": "#d8f5ff",
        "on-primary-fixed": "#001f28",
        "on-tertiary": "#472a00",
        "outline-variant": "#425154",
        "on-primary-container": "#000000",
        "surface-container-low": "#1c1b1b",
        "surface-bright": "#3a3939",
        "surface-container-highest": "#353534",
        "inverse-primary": "#00677d",
        "on-secondary-fixed-variant": "#474646",
        "surface-container-lowest": "#0e0e0e",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#ffddb8",
        "primary-fixed-dim": "#bae6ff",
        "obsidian": "#0a0a0b",
        "border": "#3a3939",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "md": "calc(var(--radius) - 2px)",
        "sm": "calc(var(--radius) - 4px)",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sync: ["Syncopate", "sans-serif"], // Keep for backward compat if needed
        inter: ["Inter", "sans-serif"],
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        marquee: "marquee 60s linear infinite",
      },
    },
  },
  plugins: [],
}
